# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }

"""
TrustMeshRegistry
------------------
This is the "main" contract of the TrustMesh network (formerly known
as GigResolve).

Deploy this contract exactly once. Instead of trusting whichever
address happens to call it, TrustMeshRegistry is a **factory**: it
deploys every TrustMeshEscrow itself via `gl.deploy_contract`, so the
set of escrow addresses it will ever listen to is fixed at the moment
of creation and can never be forged by an EOA or an unrelated
contract.

    1. `create_gig(...)` deploys a brand-new TrustMeshEscrow, records
       it in `self.escrows` immediately (the registry already knows
       every detail it needs - freelancer, client, spec_url - because
       they were passed straight into this call), and hands the new
       escrow's address back to the caller.
    2. Once a gig is settled (paid out or refunded), that same escrow
       calls `report_outcome(...)` over GenLayer's internal message
       system so the registry can update the freelancer's public
       reputation score.

--------------------------------------------------------------------
SECURITY FIX #1 (was: "Reputation Spoofing"):
--------------------------------------------------------------------
The previous design exposed a public `register_gig(...)` method that
only checked "has this sender already registered a gig?" - it never
verified the sender was an actual TrustMeshEscrow contract. That meant
any EOA could call `register_gig(...)` and then immediately call
`report_outcome(True, 100000)` to fabricate a perfect track record and
fake earnings.

That entrypoint is gone entirely. The *only* way an address can ever
become a key in `self.escrows` is by being the return value of
`gl.deploy_contract` inside `create_gig`, which only this contract
itself calls. `report_outcome` still just checks
"is `gl.message.sender_address` a key in `self.escrows`?" - but now
that check IS a real authentication, because nothing outside this
contract can ever populate that map.
--------------------------------------------------------------------

DEPLOYMENT-PORTABILITY FIX (was: "sibling-file requirement"):
--------------------------------------------------------------------
Earlier revisions of this contract read the child contract's source
off disk at call time, via
`open("/contract/trustmesh_escrow.py")` - GenLayer's documented
"Factory Pattern". That works fine for CLI/project-directory
deployments, but it silently breaks under any single-file deployment
path (such as the GenLayer Studio web UI's "Add From File" flow, which
uploads one contract in isolation with no sibling files on disk):
`create_gig` would fail with a file-not-found error the first time
anyone called it, even though the contract deployed successfully.

`trustmesh_escrow.py`'s exact source is now embedded directly in this
file as the `_TRUSTMESH_ESCROW_SOURCE` constant below, so
`trustmesh_registry.py` is fully self-contained. It deploys correctly
from a single-file upload, the CLI, a project directory, or a deploy
script - no sibling file, no disk access, no special deployment
procedure required.

>>> MAINTENANCE NOTE: if you ever edit contracts/trustmesh_escrow.py,
>>> you MUST regenerate this file afterwards so the embedded copy
>>> below stays byte-for-byte in sync with it, or `create_gig` will
>>> keep deploying a stale escrow version forever. Regenerate with:
>>>
>>>     python3 scripts/sync_escrow_source.py
>>>
>>> tests/test_embedded_source_in_sync.py checks this automatically
>>> and will fail loudly if the two ever drift apart.
--------------------------------------------------------------------
"""

from genlayer import *
from dataclasses import dataclass
import typing


# --- BEGIN embedded child-contract source (auto-generated) -----------
# This is a byte-for-byte copy of contracts/trustmesh_escrow.py,
# regenerated by scripts/sync_escrow_source.py. Do not hand-edit it -
# edit contracts/trustmesh_escrow.py itself and re-run that script.
_TRUSTMESH_ESCROW_SOURCE = r'''__ESCROW_SOURCE_PLACEHOLDER__'''
# --- END embedded child-contract source -------------------------------


@allow_storage
@dataclass
class FreelancerProfile:
    completed_gigs: u32
    disputed_gigs: u32
    reputation_score: u32
    total_earned: u256


@allow_storage
@dataclass
class GigRecord:
    freelancer: Address
    client: Address
    spec_url: str
    status: str  # "active" | "completed" | "refunded"
    amount: u256


class TrustMeshRegistry(gl.Contract):
    admin: Address
    freelancers: TreeMap[Address, FreelancerProfile]
    escrows: TreeMap[Address, GigRecord]
    escrow_addresses: DynArray[Address]
    gig_count: u32

    def __init__(self):
        self.admin = gl.message.sender_address
        self.gig_count = u32(0)

    # ------------------------------------------------------------------
    # Factory entry point - the ONLY way a gig (and its TrustMeshEscrow)
    # comes into existence. See the module docstring for why this is
    # what closes the reputation-spoofing hole.
    # ------------------------------------------------------------------
    @gl.public.write
    def create_gig(
        self,
        freelancer: str,
        client: str,
        spec_url: str,
        max_attempts: int,
        submission_deadline_seconds: int,
    ) -> str:
        escrow_code = _TRUSTMESH_ESCROW_SOURCE

        # A fresh, non-zero salt per gig so repeated calls to
        # create_gig each land on a distinct, deterministic address.
        self.gig_count = u32(self.gig_count + 1)
        salt_nonce = u256(self.gig_count)

        # on="accepted" (matching GenLayer's own documented Factory
        # Pattern) so the freshly-deployed TrustMeshEscrow is usable
        # right away, rather than a caller having to wait for this
        # create_gig transaction's own appeal window to close before
        # they can fund() the gig it just created.
        #
        # Trade-off, stated plainly: if this create_gig transaction is
        # itself later overturned on appeal, the already-spawned child
        # deployment cannot be un-deployed. In practice this is a very
        # narrow window and low-consequence here specifically, because
        # a freshly deployed TrustMeshEscrow starts in
        # "pending_funding" and holds zero GEN until a human explicitly
        # calls fund() on it - no funds are ever at risk purely because
        # of this call.
        escrow_address = gl.deploy_contract(
            code=escrow_code.encode("utf-8"),
            args=[
                freelancer,
                client,
                spec_url,
                max_attempts,
                submission_deadline_seconds,
            ],
            salt_nonce=salt_nonce,
            on="accepted",
        )

        freelancer_address = Address(freelancer)
        client_address = Address(client)

        # Because we just deployed this address ourselves, recording it
        # here - rather than waiting for the child to "phone home" the
        # way the old register_gig() did - is exactly what makes
        # report_outcome's membership check trustworthy.
        self.escrows[escrow_address] = GigRecord(
            freelancer=freelancer_address,
            client=client_address,
            spec_url=spec_url,
            status="active",
            amount=u256(0),
        )
        self.escrow_addresses.append(escrow_address)

        if freelancer_address not in self.freelancers:
            self.freelancers[freelancer_address] = FreelancerProfile(
                completed_gigs=u32(0),
                disputed_gigs=u32(0),
                reputation_score=u32(500),
                total_earned=u256(0),
            )

        return escrow_address.as_hex

    # ------------------------------------------------------------------
    # Called by a TrustMeshEscrow contract once it reaches a final
    # outcome. `escrow_address` can only be a key in `self.escrows` if
    # this registry deployed it via create_gig above, so this
    # membership check doubles as authentication - see SECURITY FIX #1
    # in the module docstring.
    # ------------------------------------------------------------------
    @gl.public.write
    def report_outcome(self, success: bool, paid_amount: int) -> None:
        escrow_address = gl.message.sender_address

        if escrow_address not in self.escrows:
            raise gl.vm.UserError("unknown escrow reporting an outcome")

        record = self.escrows[escrow_address]
        if record.status != "active":
            raise gl.vm.UserError("this gig has already been settled")

        profile = self.freelancers[record.freelancer]
        record.amount = u256(paid_amount)

        if success:
            record.status = "completed"
            profile.completed_gigs = u32(profile.completed_gigs + 1)
            profile.total_earned = u256(profile.total_earned + paid_amount)
            boosted = profile.reputation_score + 40
            profile.reputation_score = u32(boosted if boosted <= 1000 else 1000)
        else:
            record.status = "refunded"
            profile.disputed_gigs = u32(profile.disputed_gigs + 1)
            penalized = profile.reputation_score - 60
            profile.reputation_score = u32(penalized if penalized >= 0 else 0)

    # ------------------------------------------------------------------
    # Read methods
    # ------------------------------------------------------------------
    @gl.public.view
    def get_reputation(self, freelancer: str) -> dict[str, typing.Any]:
        address = Address(freelancer)
        if address not in self.freelancers:
            return {
                "completed_gigs": 0,
                "disputed_gigs": 0,
                "reputation_score": 500,
                "total_earned": 0,
            }
        profile = self.freelancers[address]
        return {
            "completed_gigs": profile.completed_gigs,
            "disputed_gigs": profile.disputed_gigs,
            "reputation_score": profile.reputation_score,
            "total_earned": profile.total_earned,
        }

    @gl.public.view
    def get_gig(self, escrow_address: str) -> dict[str, typing.Any]:
        address = Address(escrow_address)
        if address not in self.escrows:
            raise gl.vm.UserError("no gig registered for this escrow address")
        record = self.escrows[address]
        return {
            "freelancer": record.freelancer.as_hex,
            "client": record.client.as_hex,
            "spec_url": record.spec_url,
            "status": record.status,
            "amount": record.amount,
        }

    @gl.public.view
    def get_all_escrows(self) -> list[str]:
        return [address.as_hex for address in self.escrow_addresses]

    @gl.public.view
    def get_gig_count(self) -> int:
        return self.gig_count
