#!/usr/bin/env python3
"""
Regenerates contracts/trustmesh_registry.py so its embedded
`_TRUSTMESH_ESCROW_SOURCE` constant is a byte-for-byte copy of
contracts/trustmesh_escrow.py.

Why this exists
----------------
TrustMeshRegistry.create_gig() deploys TrustMeshEscrow via
`gl.deploy_contract(code=...)`. Earlier revisions read that source off
disk at call time (`open("/contract/trustmesh_escrow.py")`), which is
GenLayer's documented "Factory Pattern" - but it only works when both
files are deployed together from the same directory (e.g. via the
CLI). It breaks under any single-file deployment path, such as the
GenLayer Studio web UI's "Add From File" flow.

To make trustmesh_registry.py deployable on its own, the escrow's
source is embedded directly in it as a string constant instead. That
constant has to be regenerated by hand whenever trustmesh_escrow.py
changes, or the registry will silently keep deploying a stale escrow
version - this script does that regeneration mechanically so there's
no manual copy/paste step to get wrong.

Usage
-----
    python3 scripts/sync_escrow_source.py

Run it from anywhere inside the project; it locates files relative to
its own location, not the current working directory. It exits non-zero
(and does not touch trustmesh_registry.py) if trustmesh_escrow.py
contains anything that can't be safely embedded as a raw triple-quoted
Python string, so a bad regeneration can never happen silently.
"""

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
ESCROW_PATH = PROJECT_ROOT / "contracts" / "trustmesh_escrow.py"
REGISTRY_PATH = PROJECT_ROOT / "contracts" / "trustmesh_registry.py"
TEMPLATE_PATH = SCRIPT_DIR / "_registry_template.py"
PLACEHOLDER = "__ESCROW_SOURCE_PLACEHOLDER__"


def _load_escrow_source() -> str:
    source = ESCROW_PATH.read_text(encoding="utf-8")

    # The embedded copy is wrapped as r'''<source>''' in the template.
    # That's only safe if the source itself contains none of the
    # sequences that would break out of (or corrupt) that literal.
    problems = []
    if "'''" in source:
        problems.append(
            "contains a triple-single-quote (''') sequence, which would "
            "terminate the r'''...''' wrapper early"
        )
    if "\\" in source:
        problems.append(
            "contains a backslash, which a raw string leaves un-escaped "
            "and could change meaning when embedded"
        )
    if not source.startswith('# { "Depends"'):
        problems.append(
            "does not start with the '# { \"Depends\": ... }' GenVM "
            "version comment on its very first line - gl.deploy_contract "
            "requires this to be the literal first line of the deployed "
            "code"
        )
    if problems:
        print(
            "Refusing to regenerate trustmesh_registry.py - "
            f"{ESCROW_PATH} " + "; ".join(problems) + ".\n"
            "Fix trustmesh_escrow.py (e.g. switch to double-quoted "
            "strings, or avoid backslashes) and re-run this script.",
            file=sys.stderr,
        )
        sys.exit(1)

    return source


def main() -> None:
    escrow_source = _load_escrow_source()
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    if PLACEHOLDER not in template:
        print(
            f"{TEMPLATE_PATH} is missing the {PLACEHOLDER} marker - "
            "cannot regenerate.",
            file=sys.stderr,
        )
        sys.exit(1)

    generated = template.replace(PLACEHOLDER, escrow_source)
    REGISTRY_PATH.write_text(generated, encoding="utf-8")
    print(f"Wrote {REGISTRY_PATH} ({len(generated)} bytes).")
    print(f"Embedded {ESCROW_PATH} ({len(escrow_source)} bytes) unchanged.")


if __name__ == "__main__":
    main()
